### ISSUE TITLE
Compat issues with latest TF

### ISSUE THREAD

**Issue by kastnerkyle** [sherjilozair/char-rnn-tensorflow#31]
After building from HEAD of TF, I get some import errors for various things (almost every example on the web has this problem!)

I had to change imports in model.py to 

```
from tensorflow.python.ops import rnn_cell
from tensorflow.python.ops import seq2seq
```

Downside is that importing `tensorflow.models.rnn` raises ImportError, so something like this is probably needed to preserve backwards compat:

```
try:
    from tensorflow.models.rnn import blah
except ImportError:
    from tensorflow.python.ops import blah
```

**Comment by hunkim** [comment]
I also noticed this issue. Feel free to send PR if you know how to fix it. I guess the fix is simple.

**Comment by hunkim** [comment]
I think we can check the version something like this:

```python
import tensorflow as tf
print(tf.__version__)
```

**Comment by prestonvanloon** [comment]
I think these are under tensorflow.contrib.

This was working for me:
```python
from tensorflow.contrib import rnn
from tensorflow.contrib import seq2seq
```

**Comment by ubergarm** [comment]
Everything should be working now with TF 1.0.  The travis ci builds should help keep this repo up to date with latest TF.  

Thanks all!
