### ISSUE TITLE
Cannot train: 'tuple' object has no attribute 'eval'

### ISSUE THREAD

**Issue by wichtounet** [sherjilozair/char-rnn-tensorflow#47]
Hi, 

I tried this implementation of char-rnn and I have an issue with the train script: 

> Traceback (most recent call last):
>   File "train.py", line 111, in <module>
>     main()
>   File "train.py", line 48, in main
>     train(args)
>   File "train.py", line 93, in train
>     state = model.initial_state.eval()
> AttributeError: 'tuple' object has no attribute 'eval'

I'm using the last version of tensorflow and Python 3.4. 

Thanks

**Comment by qiubs** [comment]
try replacing the line
`           state = model.initial_state.eval()`
with 
`           model.initial_state = tf.convert_to_tensor(model.initial_state)
            state = model.initial_state.eval()`

It worked for me but I'm not sure how it would affect performance. Interestingly, I only experienced this problem when I compiled TF for use of my gpu.

**Comment by astr010** [comment]
I am using Ubuntu/Linux 64-bit CPU Only, Python 2.7 Tensorflow-0.11 and this fixed my issue

**Comment by wichtounet** [comment]
I fixed this issue using sess.run which seems to make more sense in my opinion.
