### ISSUE TITLE
 module 'tensorflow.contrib.rnn' has no attribute

### ISSUE THREAD

**Issue by vanche** [sherjilozair/char-rnn-tensorflow#86]
In my tensorflow version 0.12.1, I couldn't use "from tensorflow.contrib import rnn" and "from tensorflow.nn import legacy_seq2seq".
they were moved. 
So I used " tf.nn.rnn_cell" and "tf.nn.seq2seq" instead of above.

**Comment by sherjilozair** [comment]
Are you sure you have the latest commits? I did merge a PR which updates char-rnn to 0.12

**Comment by vanche** [comment]
thanks, after updating I can use that module
