### ISSUE TITLE
problem with --init_from

### ISSUE THREAD

**Issue by xwzy** [sherjilozair/char-rnn-tensorflow#95]
When I use --init_from=./save to restore my model, it starts to init a new model, is there anything wrong in my command?

python3 train.py --data_dir=./data/mydata --init_from=./save

**Comment by xwzy** [comment]
If I only use --init_from=./save
output is:
loading preprocessed files
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    main()
  File "train.py", line 55, in main
    train(args)
  File "train.py", line 82, in train
    assert saved_chars==data_loader.chars, "Data and loaded model disagree on character set!"
AssertionError: Data and loaded model disagree on character set!

**Comment by xwzy** [comment]
I understand what happened!

**Comment by yashjakhotiya** [comment]
Can you please explain how did you solve this issue?
